language: swift
osx_image: xcode9.1
xcode_project: SmartGO.xcworkspace
xcode_scheme: SmartGO
xcode_sdk: iphoneos11.1
podfile: Podfile

before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
  
jobs:
  include:
    - stage: Swiflint
      script:
        - ./Pods/SwiftLint/swiftlint --reporter junit
        
    - stage: XCTest
      script:
        - fastlane scan -s SwiftLint-SmartGOTests
