language: swift
osx_image: xcode9.1
xcode_project: SmartGO.xcworkspace
xcode_scheme: SmartGO
xcode_sdk: iphoneos11.1
podfile: Podfile

before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
  - gem install fastlane --no-ri --no-rdoc --no-document

script:
  - fastlane scan -s SwiftLint-SmartGOTests
