language: swift
osx_image: xcode9.1
#xcode_project: SmartGO.xcworkspace
#xcode_scheme: SmartGO
#xcode_sdk: iphoneos11.1
#podfile: Podfile

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=MyFramework/MyFramework.xcworkspace
  - IOS_SCHEME="MyFrameworkiOS"
  - IOS_SDK=iphonesimulator9.2
  - OSX_SCHEME="MyFrameworkOSX"
  - OSX_SDK=macosx10.11
  - TVOS_SCHEME="MyFrameworkTVOS"
  - TVOS_SDK=appletvsimulator9.1
  

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "SmartGO.xcworkspace" -scheme "SmartGO" -sdk "iphonesimulator11.1" -destination "OS=11.1,name=iPhone 5S" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
