language: swift
osx_image: xcode9.1
xcode_project: SmartGO.xcworkspace
xcode_scheme: SmartGOTests
xcode_sdk: iphoneos11.1
podfile: Podfile

script: xcodebuild -workspace SmartGO.xcworkspace -scheme SmartGOTests -sdk iphonesimulator -configuration Release TEST_AFTER_BUILD=YES
